# This is a basic workflow to help you get started with Actions

name: Quality

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Gr1N/setup-poetry@v4
      - run: poetry install
      - run: |
          poetry run coverage run -m pytest src
          mkdir coverage-reports
          poetry run coverage xml -o coverage-reports/coverage-tests.xml
          ls coverage-reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage-reports/coverage-tests.xml

  # This workflow contains a single job called "build"
  quality:
    needs: tests
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: coverage-reports
      - run: find .

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        with:
          projectBaseDir: src
          args: >
            -Dsonar.organization=xtofl
            -Dsonar.projectKey=xtofl_natan_mastermind
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage-tests.xml
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
